### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by jamesjennings** [pushkar/ABAGAIL#19]
Is this library meant to be released under an open source style license? Without one it's unclear what uses of this code are acceptable - can this be used in a commercial context, for example? Strictly speaking, without a license, modifying and redistributing the code are copyright infringement.

**Comment by pushkar** [comment]
ABAGAIL now has the BSD 3-Clause License. See https://github.com/pushkar/ABAGAIL/commit/1e8d6383d8dae903b0adda4d0a3650d7c0cb00b3
