### ISSUE TITLE
build fail with ant

### ISSUE THREAD

**Issue by Ryanlee88** [pushkar/ABAGAIL#52]
Line 40 and 41 of build.xml should be:

```
    <target name="javadoc" depends="prepare" >
        <javadoc sourcepath="${src.dir}" destdir="${jdocs.dir}" additionalparam="subpackages"/>
```

the current version fails when run ant.

**Comment by rob2001** [comment]
@Ryanlee88 @pushkar I'm pretty sure this has since been fixed, and this issue should be marked as closed.
